--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: gallery_galleryday; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_galleryday (
    id bigint NOT NULL,
    date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.gallery_galleryday OWNER TO postgres;

--
-- Name: gallery_galleryday_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_galleryday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_galleryday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_photogallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_photogallery (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    description character varying(100) NOT NULL,
    gallery_day_id bigint NOT NULL
);


ALTER TABLE public.gallery_photogallery OWNER TO postgres;

--
-- Name: gallery_photogallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_photogallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_photogallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_videogallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_videogallery (
    id bigint NOT NULL,
    video character varying(100) NOT NULL,
    description character varying(100) NOT NULL,
    gallery_day_id bigint NOT NULL
);


ALTER TABLE public.gallery_videogallery OWNER TO postgres;

--
-- Name: gallery_videogallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_videogallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_videogallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_answers (
    id bigint NOT NULL,
    marker character varying(10) NOT NULL,
    choice_text character varying(150) NOT NULL,
    survey_id bigint NOT NULL,
    choice_text_en_gb character varying(150),
    choice_text_uk character varying(150)
);


ALTER TABLE public.mainapp_answers OWNER TO postgres;

--
-- Name: mainapp_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_category (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    slug character varying(50) NOT NULL,
    name_en_gb character varying(30),
    name_uk character varying(30)
);


ALTER TABLE public.mainapp_category OWNER TO postgres;

--
-- Name: mainapp_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_libtext; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_libtext (
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    to_category_id bigint NOT NULL,
    content_en_gb text,
    content_uk text,
    title_en_gb character varying(30),
    title_uk character varying(30)
);


ALTER TABLE public.mainapp_libtext OWNER TO postgres;

--
-- Name: mainapp_libtext_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_libtext ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_libtext_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_personalpost; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_personalpost (
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    published_date timestamp with time zone NOT NULL,
    date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_personalpost OWNER TO postgres;

--
-- Name: mainapp_personalpost_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_personalpost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_personalpost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_post (
    published_date timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    category_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_post OWNER TO postgres;

--
-- Name: mainapp_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_survey; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_survey (
    id bigint NOT NULL,
    question character varying(150) NOT NULL,
    question_en_gb character varying(150),
    question_uk character varying(150)
);


ALTER TABLE public.mainapp_survey OWNER TO postgres;

--
-- Name: mainapp_survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_survey ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_useranswer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_useranswer (
    id bigint NOT NULL,
    answered_at timestamp with time zone NOT NULL,
    date date NOT NULL,
    answer_choice_id bigint NOT NULL,
    survey_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_useranswer OWNER TO postgres;

--
-- Name: mainapp_useranswer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_useranswer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_useranswer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_profile (
    id bigint NOT NULL,
    bio text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.users_profile OWNER TO postgres;

--
-- Name: users_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add Категорія	1	add_category
2	Can change Категорія	1	change_category
3	Can delete Категорія	1	delete_category
4	Can view Категорія	1	view_category
5	Can add survey	2	add_survey
6	Can change survey	2	change_survey
7	Can delete survey	2	delete_survey
8	Can view survey	2	view_survey
9	Can add пост з aдмінки для бібліотеки	3	add_libtext
10	Can change пост з aдмінки для бібліотеки	3	change_libtext
11	Can delete пост з aдмінки для бібліотеки	3	delete_libtext
12	Can view пост з aдмінки для бібліотеки	3	view_libtext
13	Can add answers	4	add_answers
14	Can change answers	4	change_answers
15	Can delete answers	4	delete_answers
16	Can view answers	4	view_answers
17	Can add запис користувача в бібліотеку	5	add_post
18	Can change запис користувача в бібліотеку	5	change_post
19	Can delete запис користувача в бібліотеку	5	delete_post
20	Can view запис користувача в бібліотеку	5	view_post
21	Can add ОсобистийПост	6	add_personalpost
22	Can change ОсобистийПост	6	change_personalpost
23	Can delete ОсобистийПост	6	delete_personalpost
24	Can view ОсобистийПост	6	view_personalpost
25	Can add user answer	7	add_useranswer
26	Can change user answer	7	change_useranswer
27	Can delete user answer	7	delete_useranswer
28	Can view user answer	7	view_useranswer
29	Can add profile	8	add_profile
30	Can change profile	8	change_profile
31	Can delete profile	8	delete_profile
32	Can view profile	8	view_profile
33	Can add gallery day	9	add_galleryday
34	Can change gallery day	9	change_galleryday
35	Can delete gallery day	9	delete_galleryday
36	Can view gallery day	9	view_galleryday
37	Can add photo gallery	10	add_photogallery
38	Can change photo gallery	10	change_photogallery
39	Can delete photo gallery	10	delete_photogallery
40	Can view photo gallery	10	view_photogallery
41	Can add video gallery	11	add_videogallery
42	Can change video gallery	11	change_videogallery
43	Can delete video gallery	11	delete_videogallery
44	Can view video gallery	11	view_videogallery
45	Can add log entry	12	add_logentry
46	Can change log entry	12	change_logentry
47	Can delete log entry	12	delete_logentry
48	Can view log entry	12	view_logentry
49	Can add permission	13	add_permission
50	Can change permission	13	change_permission
51	Can delete permission	13	delete_permission
52	Can view permission	13	view_permission
53	Can add group	14	add_group
54	Can change group	14	change_group
55	Can delete group	14	delete_group
56	Can view group	14	view_group
57	Can add user	15	add_user
58	Can change user	15	change_user
59	Can delete user	15	delete_user
60	Can view user	15	view_user
61	Can add content type	16	add_contenttype
62	Can change content type	16	change_contenttype
63	Can delete content type	16	delete_contenttype
64	Can view content type	16	view_contenttype
65	Can add session	17	add_session
66	Can change session	17	change_session
67	Can delete session	17	delete_session
68	Can view session	17	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$v9dBjSsBVn4LoIpUgv47W1$2GIc8zGet66774g3qFeav4RUraCtYA9UGZl1WEKDlTo=	2025-08-05 14:03:45.352013+00	f	soso	Soda	Sodo	arinaznamenok@gmail.com	f	t	2025-07-14 10:56:32.683168+00
2	pbkdf2_sha256$1000000$m6Cx00lUuPmJwxUMFObOzY$je4z2avlYbtItoT3nCtEFumx0ytHYZvNu8y2I/ENK7M=	2025-08-07 16:23:52.356751+00	t	administrator			arinacellznam@gmail.com	t	t	2025-07-21 13:48:55.059967+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-07-22 12:03:29.677724+00	1	Personal Growth	1	[{"added": {}}]	1	2
2	2025-07-22 12:03:54.890714+00	2	Relationships & Communication	1	[{"added": {}}]	1	2
3	2025-07-22 12:04:20.781174+00	3	Mental Health & Emotions	1	[{"added": {}}]	1	2
4	2025-07-22 12:06:05.886765+00	1	Personal growth	1	[{"added": {}}]	3	2
5	2025-07-22 12:06:42.394844+00	2	Healthy relationships	1	[{"added": {}}]	3	2
6	2025-07-22 12:07:14.156143+00	3	Mental health	1	[{"added": {}}]	3	2
7	2025-07-22 12:10:01.924057+00	1	How did I feel emotionally today?	1	[{"added": {}}]	2	2
8	2025-07-22 12:10:48.919722+00	1	😟 I felt anxious, overwhelmed, or irritable	1	[{"added": {}}]	4	2
9	2025-07-22 12:11:13.172186+00	2	😐 I felt mostly okay, with some ups and downs	1	[{"added": {}}]	4	2
10	2025-07-22 12:11:35.739106+00	3	😊 I felt calm, balanced, and in tune with myself	1	[{"added": {}}]	4	2
11	2025-07-22 12:12:01.403821+00	2	Did I do something just for myself today?	1	[{"added": {}}]	2	2
12	2025-07-22 12:12:59.197879+00	4	❌ No, the day was all stress or focused on others	1	[{"added": {}}]	4	2
13	2025-07-22 12:13:19.316732+00	5	⚖️ A small thing (cup of tea, walk, short break)	1	[{"added": {}}]	4	2
14	2025-07-22 12:13:40.211203+00	6	✅ Yes, I made time for myself (hobby, self-care, r	1	[{"added": {}}]	4	2
15	2025-07-22 12:14:03.864977+00	3	How was my communication with others today?	1	[{"added": {}}]	2	2
16	2025-07-22 12:14:49.835276+00	7	😠 Tense or conflictual, I didn’t feel connected	1	[{"added": {}}]	4	2
17	2025-07-22 12:15:11.407534+00	8	😐 Neutral or routine, nothing special	1	[{"added": {}}]	4	2
18	2025-07-22 12:15:30.948726+00	9	💬 I had warm, honest, supportive interactions	1	[{"added": {}}]	4	2
19	2025-07-22 12:15:55.695071+00	4	Did I accomplish anything I planned for today?	1	[{"added": {}}]	2	2
20	2025-07-22 12:16:17.993627+00	10	❌ No, I feel disappointed or unmotivated	1	[{"added": {}}]	4	2
21	2025-07-22 12:16:41.457474+00	11	🔄 Partially, I got some things done but not all	1	[{"added": {}}]	4	2
22	2025-07-22 12:17:11.526285+00	12	✅ Yes, I’m happy with my progress and results	1	[{"added": {}}]	4	2
23	2025-07-22 12:17:36.138317+00	5	How did I treat myself today?	1	[{"added": {}}]	2	2
24	2025-07-22 12:18:01.302144+00	13	🥀 I was self-critical, compared myself, or felt n	1	[{"added": {}}]	4	2
25	2025-07-22 12:18:19.317723+00	14	🤷‍♂️ I was neutral, not really paying attention t	1	[{"added": {}}]	4	2
26	2025-07-22 12:18:43.985621+00	15	🌱 I treated myself with kindness, support, and ac	1	[{"added": {}}]	4	2
27	2025-08-07 15:12:32.039931+00	14	🤷‍♂️ Був(-ла) нейтральний(-на), без особливої уваги	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]", "Choice text [en-gb]"]}}]	4	2
28	2025-08-07 15:13:33.248234+00	13	🥀 Критикував(-ла), порівнював(-ла) себе з іншими	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]", "Choice text [en-gb]"]}}]	4	2
29	2025-08-07 15:13:51.813846+00	12	✅ Так, задоволений(-на) своїм прогресом і результатами	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
30	2025-08-07 15:14:07.907841+00	15	🌱 Ставився(-лася) до себе з добротою, підтримкою	2	[{"changed": {"fields": ["Choice text [en-gb]"]}}]	4	2
31	2025-08-07 15:14:14.239188+00	14	🤷‍♂️ Був(-ла) нейтральний(-на), без особливої уваги	2	[]	4	2
32	2025-08-07 15:14:41.787211+00	11	🔄 Частково, виконав(-ла) деякі справи, але не все	2	[]	4	2
33	2025-08-07 15:15:45.471241+00	7	😠 Були конфлікти або напруга	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
34	2025-08-07 15:16:17.336515+00	6	✅ Повноцінно виділив(-ла) час для себе (хобі, турбота про себе)	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]", "Choice text [en-gb]"]}}]	4	2
35	2025-08-07 15:16:56.259235+00	5	⚖️ Зробив(-ла) щось дрібне (чай, прогулянка тощо)	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
36	2025-08-07 15:17:25.923518+00	4	❌ Зовсім нічого, день був повністю для інших	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
37	2025-08-07 15:17:49.025904+00	3	😊 Почувався(-лася) спокійно, врівноважено	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
38	2025-08-07 15:18:14.795323+00	2	😐 Почувався(-лася) більш-менш стабільно	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
39	2025-08-07 15:18:34.704699+00	1	😟 Відчував(-ла) пригніченість, тривогу або роздратування	2	[{"changed": {"fields": ["Choice text", "Choice text [uk]"]}}]	4	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	mainapp	category
2	mainapp	survey
3	mainapp	libtext
4	mainapp	answers
5	mainapp	post
6	mainapp	personalpost
7	mainapp	useranswer
8	users	profile
9	gallery	galleryday
10	gallery	photogallery
11	gallery	videogallery
12	admin	logentry
13	auth	permission
14	auth	group
15	auth	user
16	contenttypes	contenttype
17	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-14 10:18:21.890667+00
2	auth	0001_initial	2025-07-14 10:18:22.016718+00
3	admin	0001_initial	2025-07-14 10:18:22.04032+00
4	admin	0002_logentry_remove_auto_add	2025-07-14 10:18:22.049255+00
5	admin	0003_logentry_add_action_flag_choices	2025-07-14 10:18:22.064844+00
6	contenttypes	0002_remove_content_type_name	2025-07-14 10:18:22.091612+00
7	auth	0002_alter_permission_name_max_length	2025-07-14 10:18:22.106304+00
8	auth	0003_alter_user_email_max_length	2025-07-14 10:18:22.122865+00
9	auth	0004_alter_user_username_opts	2025-07-14 10:18:22.132219+00
10	auth	0005_alter_user_last_login_null	2025-07-14 10:18:22.145584+00
11	auth	0006_require_contenttypes_0002	2025-07-14 10:18:22.147581+00
12	auth	0007_alter_validators_add_error_messages	2025-07-14 10:18:22.157145+00
13	auth	0008_alter_user_username_max_length	2025-07-14 10:18:22.172861+00
14	auth	0009_alter_user_last_name_max_length	2025-07-14 10:18:22.182511+00
15	auth	0010_alter_group_name_max_length	2025-07-14 10:18:22.195268+00
16	auth	0011_update_proxy_permissions	2025-07-14 10:18:22.203731+00
17	auth	0012_alter_user_first_name_max_length	2025-07-14 10:18:22.215898+00
18	gallery	0001_initial	2025-07-14 10:18:22.292356+00
19	gallery	0002_alter_videogallery_video	2025-07-14 10:18:22.301966+00
20	gallery	0003_alter_photogallery_image_alter_videogallery_video	2025-07-14 10:18:22.32086+00
21	mainapp	0001_initial	2025-07-14 10:18:22.486356+00
22	mainapp	0002_alter_personalpost_unique_together_and_more	2025-07-14 10:18:22.536029+00
23	mainapp	0003_remove_post_poster	2025-07-14 10:18:22.555005+00
24	mainapp	0004_alter_post_options_answers_choice_text_en_gb_and_more	2025-07-14 10:18:22.637031+00
25	mainapp	0005_alter_libtext_options	2025-07-14 10:18:22.645375+00
26	mainapp	0006_alter_libtext_to_category	2025-07-14 10:18:22.677418+00
27	mainapp	0007_alter_libtext_title_alter_libtext_title_en_gb_and_more	2025-07-14 10:18:22.847582+00
28	mainapp	0008_remove_post_teg_delete_teg	2025-07-14 10:18:22.868028+00
29	sessions	0001_initial	2025-07-14 10:18:22.87865+00
30	users	0001_initial	2025-07-14 10:18:22.916116+00
31	mainapp	0009_alter_answers_choice_text_and_more	2025-08-07 15:12:27.345689+00
32	users	0002_remove_profile_avatar	2025-08-08 13:59:05.98125+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ye6mvhoedf6wrbujhk4nulcn25006zpg	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uh2Oh:2udWr9Ej-VcL-Ig-jRnVFUI1EBoo1vXi4CO2bv-kVuE	2025-08-13 08:42:51.726114+00
6a3fxhbnjgbdsjh8puoct30fpbkx0g43	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uh2bo:O5V94x8Vitt1xB-v_IgHmelkFxS2XauAo_RN07iADlE	2025-08-13 08:56:24.086621+00
cb87bygcaqz3vwxtqua4jdc1jfxcm6jk	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uh2f1:PUH3j05e0qPbPBtkuS0LX7LiZ__jraiGkzBqjrORuuI	2025-08-13 08:59:43.454375+00
ld7yn07k0h3rwtfoz54h6ypvnesvilz6	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uk2Ej:QFzj5SJ76Pv670a6t8kC-mg-7j0IRPloNtdXCNiaC3c	2025-08-21 15:08:57.089471+00
63nmzef20vqso4awbu84he62siy1qnl1	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uk2mD:44olVNfZDlSP-VLmUEwR3Ojq7q_uWaY0zzRilh8WdWs	2025-08-21 15:43:33.897754+00
uv0ugh1i4pix4rkfmyleidxo457bbw5u	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uk2rQ:2qMjJ3Gg-ZbXhga5yEH8bsZX8coGQ5fmvNV7hurrgeI	2025-08-21 15:48:56.286724+00
uh4ixaofqltifohwe3dxb3x75s2ut605	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uk3Dq:uaNqEcQWmMHLcNcnQpZA4abObuo2zfVGRjO8BfsKmLc	2025-08-21 16:12:06.797063+00
bx6yktk9wpwv7as0d2ls8evnfvjrn55z	.eJxVjEEOwiAQRe_C2hBGSqe4dN8zkBkGpGpoUtqV8e7apAvd_vfef6lA21rC1tISJlEXdVan340pPlLdgdyp3mYd57ouE-td0QdtepwlPa-H-3dQqJVv7bOxgj5m04N1nQB5RADMJolz2FmbDLEDSBli5jiIIHr2Xohp6Fm9P9cnODw:1uk3PE:QOvVuBGxfPRZlxBoCFPiVoW3eEFwrZq-kHnv45DnRqI	2025-08-21 16:23:52.366532+00
\.


--
-- Data for Name: gallery_galleryday; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_galleryday (id, date, user_id) FROM stdin;
1	2025-07-14	1
2	2025-07-22	2
3	2025-08-05	1
\.


--
-- Data for Name: gallery_photogallery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_photogallery (id, image, description, gallery_day_id) FROM stdin;
1	photos/Screenshot_from_2025-07-14_13-57-26.png		1
2	photos/photo_1_2025-07-22_15-21-30.jpg		2
3	photos/photo_2_2025-07-22_15-21-30.jpg		2
4	photos/photo_3_2025-07-22_15-21-30.jpg		2
5	photos/photo_4_2025-07-22_15-21-30.jpg		2
6	photos/photo_5_2025-07-22_15-21-30.jpg		2
7	photos/Screenshot_from_2025-07-14_13-57-26_hrcHivm.png		3
8	photos/Screenshot_from_2025-07-14_14-04-28.png		3
9	photos/Screenshot_from_2025-07-16_19-02-47.png		3
10	photos/Screenshot_from_2025-07-17_16-44-47.png		3
11	photos/Screenshot_from_2025-07-21_16-14-10.png		3
\.


--
-- Data for Name: gallery_videogallery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_videogallery (id, video, description, gallery_day_id) FROM stdin;
1	videos/IMG_3282.MP4		2
2	videos/IMG_3283.MP4		2
\.


--
-- Data for Name: mainapp_answers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_answers (id, marker, choice_text, survey_id, choice_text_en_gb, choice_text_uk) FROM stdin;
8	neutral	😐 Neutral or routine, nothing special	3	😐 Neutral or routine, nothing special	😐 Спілкування було звичним, без особливої глибини
9	good	💬 I had warm, honest, supportive interactions	3	💬 I had warm, honest, supportive interactions	💬 Мав(-ла) теплі, щирі, підтримуючі взаємодії
10	bad	❌ No, I feel disappointed or unmotivated	4	❌ No, I feel disappointed or unmotivated	❌ Ні, відчуваю розчарування або прокрастинацію
13	bad	🥀 Критикував(-ла), порівнював(-ла) себе з іншими	5	🥀 I was self-critical	🥀 Критикував(-ла), порівнював(-ла) себе з іншими
12	good	✅ Так, задоволений(-на) своїм прогресом і результатами	4	✅ Yes, I’m happy with my progress and results	✅ Так, задоволений(-на) своїм прогресом і результатами
15	good	🌱 Ставився(-лася) до себе з добротою, підтримкою	5	🌱 I treated myself with kindness, support	🌱 Ставився(-лася) до себе з добротою, підтримкою
14	neutral	🤷‍♂️ Був(-ла) нейтральний(-на), без особливої уваги	5	🤷‍♂️ I was neutral, not really paying attention	🤷‍♂️ Був(-ла) нейтральний(-на), без особливої уваги
11	neutral	🔄 Частково, виконав(-ла) деякі справи, але не все	4	🔄 Partially, I got some things done but not all	🔄 Частково, виконав(-ла) деякі справи, але не все
7	bad	😠 Були конфлікти або напруга	3	😠 Tense or conflictual, I didn’t feel connected	😠 Були конфлікти або напруга
6	good	✅ Повноцінно виділив(-ла) час для себе (хобі, турбота про себе)	2	✅ Yes, I made time for myself (hobby, self-care)	✅ Повноцінно виділив(-ла) час для себе (хобі, турбота про себе)
5	neutral	⚖️ Зробив(-ла) щось дрібне (чай, прогулянка тощо)	2	⚖️ A small thing (cup of tea, walk, short break)	⚖️ Зробив(-ла) щось дрібне (чай, прогулянка тощо)
4	bad	❌ Зовсім нічого, день був повністю для інших	2	❌ No, the day was all stress or focused on others	❌ Зовсім нічого, день був повністю для інших
3	good	😊 Почувався(-лася) спокійно, врівноважено	1	😊 I felt calm, balanced, and in tune with myself	😊 Почувався(-лася) спокійно, врівноважено
2	neutral	😐 Почувався(-лася) більш-менш стабільно	1	😐 I felt mostly okay, with some ups and downs	😐 Почувався(-лася) більш-менш стабільно
1	bad	😟 Відчував(-ла) пригніченість, тривогу або роздратування	1	😟 I felt anxious, overwhelmed, or irritable	😟 Відчував(-ла) пригніченість, тривогу або роздратування
\.


--
-- Data for Name: mainapp_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_category (id, name, slug, name_en_gb, name_uk) FROM stdin;
1	Personal Growth	PersonalGrowth	Personal Growth	Особистісний розвиток
2	Relationships & Communication	RelationshipsCommunication	Relationships & Communication	Стосунки та комунікація
3	Mental Health & Emotions	MentalHealthEmotions	Mental Health & Emotions	Психічне здоров’я та емоції
\.


--
-- Data for Name: mainapp_libtext; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_libtext (id, title, content, to_category_id, content_en_gb, content_uk, title_en_gb, title_uk) FROM stdin;
1	Personal growth	Personal growth helps us better understand ourselves and our needs.\r\nIt is a path toward self-realization, confidence, and inner balance.\r\nIn the process, we learn to set goals, overcome fears, and grow beyond our limits.\r\nIt's important to reflect on our values and life priorities.\r\nEach step on this path makes us stronger and more free.	1	Personal growth helps us better understand ourselves and our needs.\r\nIt is a path toward self-realization, confidence, and inner balance.\r\nIn the process, we learn to set goals, overcome fears, and grow beyond our limits.\r\nIt's important to reflect on our values and life priorities.\r\nEach step on this path makes us stronger and more free.	Особистісний розвиток допомагає нам краще розуміти себе та свої потреби.\r\nЦе шлях до самореалізації, впевненості в собі та внутрішньої рівноваги.\r\nУ процесі розвитку ми вчимося ставити цілі, долати страхи й зростати над собою.\r\nВажливо приділяти увагу власним цінностям і життєвим пріоритетам.\r\nКожен крок на цьому шляху робить нас сильнішими та вільнішими.	Personal growth	Особистісний розвиток
2	Healthy relationships	Healthy relationships are built on trust, respect, and open communication.\r\nThe ability to listen and express feelings helps avoid conflicts.\r\nCommunication is not just about words — tone, body language, and emotions matter too.\r\nIt's important to learn how to set personal boundaries and care for yourself in relationships.\r\nThe deeper our connections with others, the more support and joy we experience.	2	Healthy relationships are built on trust, respect, and open communication.\r\nThe ability to listen and express feelings helps avoid conflicts.\r\nCommunication is not just about words — tone, body language, and emotions matter too.\r\nIt's important to learn how to set personal boundaries and care for yourself in relationships.\r\nThe deeper our connections with others, the more support and joy we experience.	Здорові стосунки будуються на довірі, повазі та відкритій комунікації.\r\nВміння слухати й висловлювати свої почуття допомагає уникати конфліктів.\r\nКомунікація — це не лише слова, а й тон, мова тіла та емоції.\r\nВарто вчитися встановлювати особисті межі та дбати про себе в стосунках.\r\nЧим глибші наші зв’язки з іншими, тим більше підтримки й радості ми відчуваємо.	Healthy relationships	Здорові стосунки
3	Mental health	Mental health is just as important as physical health.\r\nEmotions signal our inner state and help us understand ourselves.\r\nIt’s important to allow ourselves to feel and talk about difficult experiences.\r\nAnxiety, stress, or sadness are not weaknesses but natural parts of being human.\r\nSupport from a professional or loved ones can be the first step toward healing.	3	Mental health is just as important as physical health.\r\nEmotions signal our inner state and help us understand ourselves.\r\nIt’s important to allow ourselves to feel and talk about difficult experiences.\r\nAnxiety, stress, or sadness are not weaknesses but natural parts of being human.\r\nSupport from a professional or loved ones can be the first step toward healing.	Психічне здоров’я — це така ж важлива частина життя, як і фізичне.\r\nЕмоції сигналізують про наш стан і допомагають зрозуміти себе.\r\nВажливо дозволяти собі відчувати й говорити про складні переживання.\r\nТривога, стрес чи сум — це не слабкість, а нормальна частина людського досвіду.\r\nПідтримка фахівця або близьких може стати першим кроком до зцілення.	Mental health	Психічне здоров’я
\.


--
-- Data for Name: mainapp_personalpost; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_personalpost (id, title, content, published_date, date, user_id) FROM stdin;
1	fg	fgdfg	2025-07-14 10:57:10.724362+00	2025-07-14	1
2	Easy Day	I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits. I like to paint and eat fruits.	2025-07-22 12:23:14.639192+00	2025-07-22	2
3	Hoho	nlanlanlanlanla	2025-08-05 13:45:08.81565+00	2025-08-05	1
4	fhfh	dfjdfj	2025-08-07 11:32:41.007817+00	2025-08-07	1
\.


--
-- Data for Name: mainapp_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_post (published_date, id, title, content, category_id, user_id) FROM stdin;
2025-07-22 12:26:15.122247+00	1	Free time	Personal growth often begins in how we choose to spend our free time.\r\nInstead of just filling it with distractions, we can use it to learn, reflect, or create.\r\nMoments of quiet and rest help us reconnect with ourselves and our goals.\r\nFree time is not wasted when it’s used to support our well-being and inner development.\r\nBy using our time mindfully, we invest in a stronger, wiser version of ourselves.	1	2
2025-07-22 13:17:16.600291+00	2	Mental health+animals	Spending time with animals can greatly improve mental well-being by reducing stress and anxiety. Pets offer companionship and unconditional love, helping to ease feelings of loneliness and depression. Caring for animals also encourages healthy routines and a sense of responsibility, which supports those facing mental health struggles. Interacting with therapy animals has been shown to boost mood and promote relaxation. Animals provide non-judgmental support, making them comforting friends during difficult emotional times.	3	1
\.


--
-- Data for Name: mainapp_survey; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_survey (id, question, question_en_gb, question_uk) FROM stdin;
1	How did I feel emotionally today?	How did I feel emotionally today?	Як я сьогодні почувався/почувалася емоційно?
2	Did I do something just for myself today?	Did I do something just for myself today?	Чи вдалося мені сьогодні зробити щось для себе?
3	How was my communication with others today?	How was my communication with others today?	Як я сьогодні спілкувався(-лася) з іншими?
4	Did I accomplish anything I planned for today?	Did I accomplish anything I planned for today?	Чи досяг(-ла) я сьогодні чогось, що запланував(-ла)?
5	How did I treat myself today?	How did I treat myself today?	Як я сьогодні ставився(-лася) до себе?
\.


--
-- Data for Name: mainapp_useranswer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_useranswer (id, answered_at, date, answer_choice_id, survey_id, user_id) FROM stdin;
1	2025-07-22 12:23:47.483726+00	2025-07-22	3	1	2
2	2025-07-22 12:23:47.483796+00	2025-07-22	6	2	2
3	2025-07-22 12:23:47.48383+00	2025-07-22	8	3	2
4	2025-07-22 12:23:47.48386+00	2025-07-22	12	4	2
5	2025-07-22 12:23:47.483889+00	2025-07-22	14	5	2
6	2025-08-05 13:44:21.529634+00	2025-08-05	2	1	1
7	2025-08-05 13:44:21.529676+00	2025-08-05	6	2	1
8	2025-08-05 13:44:21.529694+00	2025-08-05	9	3	1
9	2025-08-05 13:44:21.529708+00	2025-08-05	12	4	1
10	2025-08-05 13:44:21.529722+00	2025-08-05	14	5	1
\.


--
-- Data for Name: users_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_profile (id, bio, user_id) FROM stdin;
1		1
2	моє біобіобіобіоб	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 39, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: gallery_galleryday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_galleryday_id_seq', 3, true);


--
-- Name: gallery_photogallery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_photogallery_id_seq', 11, true);


--
-- Name: gallery_videogallery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_videogallery_id_seq', 2, true);


--
-- Name: mainapp_answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_answers_id_seq', 15, true);


--
-- Name: mainapp_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_category_id_seq', 3, true);


--
-- Name: mainapp_libtext_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_libtext_id_seq', 3, true);


--
-- Name: mainapp_personalpost_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_personalpost_id_seq', 4, true);


--
-- Name: mainapp_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_post_id_seq', 2, true);


--
-- Name: mainapp_survey_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_survey_id_seq', 5, true);


--
-- Name: mainapp_useranswer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_useranswer_id_seq', 10, true);


--
-- Name: users_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_profile_id_seq', 2, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gallery_galleryday gallery_galleryday_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_pkey PRIMARY KEY (id);


--
-- Name: gallery_galleryday gallery_galleryday_user_id_date_33b0b1e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_user_id_date_33b0b1e8_uniq UNIQUE (user_id, date);


--
-- Name: gallery_photogallery gallery_photogallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_photogallery
    ADD CONSTRAINT gallery_photogallery_pkey PRIMARY KEY (id);


--
-- Name: gallery_videogallery gallery_videogallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_videogallery
    ADD CONSTRAINT gallery_videogallery_pkey PRIMARY KEY (id);


--
-- Name: mainapp_answers mainapp_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_answers
    ADD CONSTRAINT mainapp_answers_pkey PRIMARY KEY (id);


--
-- Name: mainapp_category mainapp_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_category
    ADD CONSTRAINT mainapp_category_pkey PRIMARY KEY (id);


--
-- Name: mainapp_category mainapp_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_category
    ADD CONSTRAINT mainapp_category_slug_key UNIQUE (slug);


--
-- Name: mainapp_libtext mainapp_libtext_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_libtext
    ADD CONSTRAINT mainapp_libtext_pkey PRIMARY KEY (id);


--
-- Name: mainapp_personalpost mainapp_personalpost_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_pkey PRIMARY KEY (id);


--
-- Name: mainapp_personalpost mainapp_personalpost_user_id_date_content_555c10f2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_user_id_date_content_555c10f2_uniq UNIQUE (user_id, date, content);


--
-- Name: mainapp_post mainapp_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_pkey PRIMARY KEY (id);


--
-- Name: mainapp_survey mainapp_survey_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_survey
    ADD CONSTRAINT mainapp_survey_pkey PRIMARY KEY (id);


--
-- Name: mainapp_useranswer mainapp_useranswer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_pkey PRIMARY KEY (id);


--
-- Name: mainapp_useranswer mainapp_useranswer_user_id_survey_id_date_a92331d0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_user_id_survey_id_date_a92331d0_uniq UNIQUE (user_id, survey_id, date);


--
-- Name: users_profile users_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: gallery_galleryday_user_id_6c0e1533; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_galleryday_user_id_6c0e1533 ON public.gallery_galleryday USING btree (user_id);


--
-- Name: gallery_photogallery_gallery_day_id_7651b352; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_photogallery_gallery_day_id_7651b352 ON public.gallery_photogallery USING btree (gallery_day_id);


--
-- Name: gallery_videogallery_gallery_day_id_a0bb34a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_videogallery_gallery_day_id_a0bb34a2 ON public.gallery_videogallery USING btree (gallery_day_id);


--
-- Name: mainapp_answers_survey_id_7710a3df; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_answers_survey_id_7710a3df ON public.mainapp_answers USING btree (survey_id);


--
-- Name: mainapp_category_slug_27883014_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_category_slug_27883014_like ON public.mainapp_category USING btree (slug varchar_pattern_ops);


--
-- Name: mainapp_libtext_to_category_id_839e8ee3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_libtext_to_category_id_839e8ee3 ON public.mainapp_libtext USING btree (to_category_id);


--
-- Name: mainapp_personalpost_user_id_dfbde4a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_personalpost_user_id_dfbde4a3 ON public.mainapp_personalpost USING btree (user_id);


--
-- Name: mainapp_post_category_id_1581664c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_post_category_id_1581664c ON public.mainapp_post USING btree (category_id);


--
-- Name: mainapp_post_user_id_5cd7dbd4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_post_user_id_5cd7dbd4 ON public.mainapp_post USING btree (user_id);


--
-- Name: mainapp_useranswer_answer_choice_id_170ad836; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_answer_choice_id_170ad836 ON public.mainapp_useranswer USING btree (answer_choice_id);


--
-- Name: mainapp_useranswer_survey_id_511eb38b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_survey_id_511eb38b ON public.mainapp_useranswer USING btree (survey_id);


--
-- Name: mainapp_useranswer_user_id_f5fa355a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_user_id_f5fa355a ON public.mainapp_useranswer USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_galleryday gallery_galleryday_user_id_6c0e1533_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_user_id_6c0e1533_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_photogallery gallery_photogallery_gallery_day_id_7651b352_fk_gallery_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_photogallery
    ADD CONSTRAINT gallery_photogallery_gallery_day_id_7651b352_fk_gallery_g FOREIGN KEY (gallery_day_id) REFERENCES public.gallery_galleryday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_videogallery gallery_videogallery_gallery_day_id_a0bb34a2_fk_gallery_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_videogallery
    ADD CONSTRAINT gallery_videogallery_gallery_day_id_a0bb34a2_fk_gallery_g FOREIGN KEY (gallery_day_id) REFERENCES public.gallery_galleryday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_answers mainapp_answers_survey_id_7710a3df_fk_mainapp_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_answers
    ADD CONSTRAINT mainapp_answers_survey_id_7710a3df_fk_mainapp_survey_id FOREIGN KEY (survey_id) REFERENCES public.mainapp_survey(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_libtext mainapp_libtext_to_category_id_839e8ee3_fk_mainapp_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_libtext
    ADD CONSTRAINT mainapp_libtext_to_category_id_839e8ee3_fk_mainapp_category_id FOREIGN KEY (to_category_id) REFERENCES public.mainapp_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_personalpost mainapp_personalpost_user_id_dfbde4a3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_user_id_dfbde4a3_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_post mainapp_post_category_id_1581664c_fk_mainapp_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_category_id_1581664c_fk_mainapp_category_id FOREIGN KEY (category_id) REFERENCES public.mainapp_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_post mainapp_post_user_id_5cd7dbd4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_user_id_5cd7dbd4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_answer_choice_id_170ad836_fk_mainapp_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_answer_choice_id_170ad836_fk_mainapp_a FOREIGN KEY (answer_choice_id) REFERENCES public.mainapp_answers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_survey_id_511eb38b_fk_mainapp_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_survey_id_511eb38b_fk_mainapp_survey_id FOREIGN KEY (survey_id) REFERENCES public.mainapp_survey(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_user_id_f5fa355a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_user_id_f5fa355a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_profile users_profile_user_id_2112e78d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_2112e78d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

