--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: gallery_galleryday; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_galleryday (
    id bigint NOT NULL,
    date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.gallery_galleryday OWNER TO postgres;

--
-- Name: gallery_galleryday_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_galleryday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_galleryday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_photogallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_photogallery (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    description character varying(100) NOT NULL,
    gallery_day_id bigint NOT NULL
);


ALTER TABLE public.gallery_photogallery OWNER TO postgres;

--
-- Name: gallery_photogallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_photogallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_photogallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_videogallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_videogallery (
    id bigint NOT NULL,
    video character varying(100) NOT NULL,
    description character varying(100) NOT NULL,
    gallery_day_id bigint NOT NULL
);


ALTER TABLE public.gallery_videogallery OWNER TO postgres;

--
-- Name: gallery_videogallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_videogallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_videogallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_answers (
    id bigint NOT NULL,
    marker character varying(10) NOT NULL,
    choice_text character varying(150) NOT NULL,
    survey_id bigint NOT NULL,
    choice_text_en_gb character varying(150),
    choice_text_uk character varying(150)
);


ALTER TABLE public.mainapp_answers OWNER TO postgres;

--
-- Name: mainapp_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_category (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    slug character varying(50) NOT NULL,
    name_en_gb character varying(30),
    name_uk character varying(30)
);


ALTER TABLE public.mainapp_category OWNER TO postgres;

--
-- Name: mainapp_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_libtext; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_libtext (
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    to_category_id bigint NOT NULL,
    content_en_gb text,
    content_uk text,
    title_en_gb character varying(30),
    title_uk character varying(30)
);


ALTER TABLE public.mainapp_libtext OWNER TO postgres;

--
-- Name: mainapp_libtext_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_libtext ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_libtext_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_personalpost; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_personalpost (
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    published_date timestamp with time zone NOT NULL,
    date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_personalpost OWNER TO postgres;

--
-- Name: mainapp_personalpost_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_personalpost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_personalpost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_post (
    published_date timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    title character varying(30) NOT NULL,
    content text NOT NULL,
    category_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_post OWNER TO postgres;

--
-- Name: mainapp_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_survey; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_survey (
    id bigint NOT NULL,
    question character varying(150) NOT NULL,
    question_en_gb character varying(150),
    question_uk character varying(150)
);


ALTER TABLE public.mainapp_survey OWNER TO postgres;

--
-- Name: mainapp_survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_survey ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_useranswer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mainapp_useranswer (
    id bigint NOT NULL,
    answered_at timestamp with time zone NOT NULL,
    date date NOT NULL,
    answer_choice_id bigint NOT NULL,
    survey_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mainapp_useranswer OWNER TO postgres;

--
-- Name: mainapp_useranswer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mainapp_useranswer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_useranswer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_profile (
    id bigint NOT NULL,
    bio text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.users_profile OWNER TO postgres;

--
-- Name: users_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add Категорія	1	add_category
2	Can change Категорія	1	change_category
3	Can delete Категорія	1	delete_category
4	Can view Категорія	1	view_category
5	Can add survey	2	add_survey
6	Can change survey	2	change_survey
7	Can delete survey	2	delete_survey
8	Can view survey	2	view_survey
9	Can add пост з aдмінки для бібліотеки	3	add_libtext
10	Can change пост з aдмінки для бібліотеки	3	change_libtext
11	Can delete пост з aдмінки для бібліотеки	3	delete_libtext
12	Can view пост з aдмінки для бібліотеки	3	view_libtext
13	Can add answers	4	add_answers
14	Can change answers	4	change_answers
15	Can delete answers	4	delete_answers
16	Can view answers	4	view_answers
17	Can add запис користувача в бібліотеку	5	add_post
18	Can change запис користувача в бібліотеку	5	change_post
19	Can delete запис користувача в бібліотеку	5	delete_post
20	Can view запис користувача в бібліотеку	5	view_post
21	Can add ОсобистийПост	6	add_personalpost
22	Can change ОсобистийПост	6	change_personalpost
23	Can delete ОсобистийПост	6	delete_personalpost
24	Can view ОсобистийПост	6	view_personalpost
25	Can add user answer	7	add_useranswer
26	Can change user answer	7	change_useranswer
27	Can delete user answer	7	delete_useranswer
28	Can view user answer	7	view_useranswer
29	Can add profile	8	add_profile
30	Can change profile	8	change_profile
31	Can delete profile	8	delete_profile
32	Can view profile	8	view_profile
33	Can add gallery day	9	add_galleryday
34	Can change gallery day	9	change_galleryday
35	Can delete gallery day	9	delete_galleryday
36	Can view gallery day	9	view_galleryday
37	Can add photo gallery	10	add_photogallery
38	Can change photo gallery	10	change_photogallery
39	Can delete photo gallery	10	delete_photogallery
40	Can view photo gallery	10	view_photogallery
41	Can add video gallery	11	add_videogallery
42	Can change video gallery	11	change_videogallery
43	Can delete video gallery	11	delete_videogallery
44	Can view video gallery	11	view_videogallery
45	Can add log entry	12	add_logentry
46	Can change log entry	12	change_logentry
47	Can delete log entry	12	delete_logentry
48	Can view log entry	12	view_logentry
49	Can add permission	13	add_permission
50	Can change permission	13	change_permission
51	Can delete permission	13	delete_permission
52	Can view permission	13	view_permission
53	Can add group	14	add_group
54	Can change group	14	change_group
55	Can delete group	14	delete_group
56	Can view group	14	view_group
57	Can add user	15	add_user
58	Can change user	15	change_user
59	Can delete user	15	delete_user
60	Can view user	15	view_user
61	Can add content type	16	add_contenttype
62	Can change content type	16	change_contenttype
63	Can delete content type	16	delete_contenttype
64	Can view content type	16	view_contenttype
65	Can add session	17	add_session
66	Can change session	17	change_session
67	Can delete session	17	delete_session
68	Can view session	17	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	mainapp	category
2	mainapp	survey
3	mainapp	libtext
4	mainapp	answers
5	mainapp	post
6	mainapp	personalpost
7	mainapp	useranswer
8	users	profile
9	gallery	galleryday
10	gallery	photogallery
11	gallery	videogallery
12	admin	logentry
13	auth	permission
14	auth	group
15	auth	user
16	contenttypes	contenttype
17	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-08-12 16:11:07.743142+00
2	auth	0001_initial	2025-08-12 16:11:07.856941+00
3	admin	0001_initial	2025-08-12 16:11:07.891036+00
4	admin	0002_logentry_remove_auto_add	2025-08-12 16:11:07.899277+00
5	admin	0003_logentry_add_action_flag_choices	2025-08-12 16:11:07.91376+00
6	contenttypes	0002_remove_content_type_name	2025-08-12 16:11:07.927322+00
7	auth	0002_alter_permission_name_max_length	2025-08-12 16:11:07.934745+00
8	auth	0003_alter_user_email_max_length	2025-08-12 16:11:07.942059+00
9	auth	0004_alter_user_username_opts	2025-08-12 16:11:07.949869+00
10	auth	0005_alter_user_last_login_null	2025-08-12 16:11:07.963351+00
11	auth	0006_require_contenttypes_0002	2025-08-12 16:11:07.976661+00
12	auth	0007_alter_validators_add_error_messages	2025-08-12 16:11:07.993395+00
13	auth	0008_alter_user_username_max_length	2025-08-12 16:11:08.077935+00
14	auth	0009_alter_user_last_name_max_length	2025-08-12 16:11:08.099179+00
15	auth	0010_alter_group_name_max_length	2025-08-12 16:11:08.133349+00
16	auth	0011_update_proxy_permissions	2025-08-12 16:11:08.155241+00
17	auth	0012_alter_user_first_name_max_length	2025-08-12 16:11:08.175667+00
18	gallery	0001_initial	2025-08-12 16:11:08.265978+00
19	gallery	0002_alter_videogallery_video	2025-08-12 16:11:08.27142+00
20	gallery	0003_alter_photogallery_image_alter_videogallery_video	2025-08-12 16:11:08.282032+00
21	mainapp	0001_initial	2025-08-12 16:11:08.469652+00
22	mainapp	0002_alter_personalpost_unique_together_and_more	2025-08-12 16:11:08.525633+00
23	mainapp	0003_remove_post_poster	2025-08-12 16:11:08.539356+00
24	mainapp	0004_alter_post_options_answers_choice_text_en_gb_and_more	2025-08-12 16:11:08.586735+00
25	mainapp	0005_alter_libtext_options	2025-08-12 16:11:08.595607+00
26	mainapp	0006_alter_libtext_to_category	2025-08-12 16:11:08.612131+00
27	mainapp	0007_alter_libtext_title_alter_libtext_title_en_gb_and_more	2025-08-12 16:11:08.751951+00
28	mainapp	0008_remove_post_teg_delete_teg	2025-08-12 16:11:08.791026+00
29	mainapp	0009_alter_answers_choice_text_and_more	2025-08-12 16:11:08.809588+00
30	sessions	0001_initial	2025-08-12 16:11:08.82293+00
31	users	0001_initial	2025-08-12 16:11:08.849541+00
32	users	0002_remove_profile_avatar	2025-08-12 16:11:08.859556+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: gallery_galleryday; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_galleryday (id, date, user_id) FROM stdin;
\.


--
-- Data for Name: gallery_photogallery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_photogallery (id, image, description, gallery_day_id) FROM stdin;
\.


--
-- Data for Name: gallery_videogallery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gallery_videogallery (id, video, description, gallery_day_id) FROM stdin;
\.


--
-- Data for Name: mainapp_answers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_answers (id, marker, choice_text, survey_id, choice_text_en_gb, choice_text_uk) FROM stdin;
\.


--
-- Data for Name: mainapp_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_category (id, name, slug, name_en_gb, name_uk) FROM stdin;
\.


--
-- Data for Name: mainapp_libtext; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_libtext (id, title, content, to_category_id, content_en_gb, content_uk, title_en_gb, title_uk) FROM stdin;
\.


--
-- Data for Name: mainapp_personalpost; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_personalpost (id, title, content, published_date, date, user_id) FROM stdin;
\.


--
-- Data for Name: mainapp_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_post (published_date, id, title, content, category_id, user_id) FROM stdin;
\.


--
-- Data for Name: mainapp_survey; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_survey (id, question, question_en_gb, question_uk) FROM stdin;
\.


--
-- Data for Name: mainapp_useranswer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mainapp_useranswer (id, answered_at, date, answer_choice_id, survey_id, user_id) FROM stdin;
\.


--
-- Data for Name: users_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_profile (id, bio, user_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: gallery_galleryday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_galleryday_id_seq', 1, false);


--
-- Name: gallery_photogallery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_photogallery_id_seq', 1, false);


--
-- Name: gallery_videogallery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gallery_videogallery_id_seq', 1, false);


--
-- Name: mainapp_answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_answers_id_seq', 1, false);


--
-- Name: mainapp_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_category_id_seq', 1, false);


--
-- Name: mainapp_libtext_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_libtext_id_seq', 1, false);


--
-- Name: mainapp_personalpost_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_personalpost_id_seq', 1, false);


--
-- Name: mainapp_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_post_id_seq', 1, false);


--
-- Name: mainapp_survey_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_survey_id_seq', 1, false);


--
-- Name: mainapp_useranswer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mainapp_useranswer_id_seq', 1, false);


--
-- Name: users_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_profile_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gallery_galleryday gallery_galleryday_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_pkey PRIMARY KEY (id);


--
-- Name: gallery_galleryday gallery_galleryday_user_id_date_33b0b1e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_user_id_date_33b0b1e8_uniq UNIQUE (user_id, date);


--
-- Name: gallery_photogallery gallery_photogallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_photogallery
    ADD CONSTRAINT gallery_photogallery_pkey PRIMARY KEY (id);


--
-- Name: gallery_videogallery gallery_videogallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_videogallery
    ADD CONSTRAINT gallery_videogallery_pkey PRIMARY KEY (id);


--
-- Name: mainapp_answers mainapp_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_answers
    ADD CONSTRAINT mainapp_answers_pkey PRIMARY KEY (id);


--
-- Name: mainapp_category mainapp_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_category
    ADD CONSTRAINT mainapp_category_pkey PRIMARY KEY (id);


--
-- Name: mainapp_category mainapp_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_category
    ADD CONSTRAINT mainapp_category_slug_key UNIQUE (slug);


--
-- Name: mainapp_libtext mainapp_libtext_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_libtext
    ADD CONSTRAINT mainapp_libtext_pkey PRIMARY KEY (id);


--
-- Name: mainapp_personalpost mainapp_personalpost_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_pkey PRIMARY KEY (id);


--
-- Name: mainapp_personalpost mainapp_personalpost_user_id_date_content_555c10f2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_user_id_date_content_555c10f2_uniq UNIQUE (user_id, date, content);


--
-- Name: mainapp_post mainapp_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_pkey PRIMARY KEY (id);


--
-- Name: mainapp_survey mainapp_survey_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_survey
    ADD CONSTRAINT mainapp_survey_pkey PRIMARY KEY (id);


--
-- Name: mainapp_useranswer mainapp_useranswer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_pkey PRIMARY KEY (id);


--
-- Name: mainapp_useranswer mainapp_useranswer_user_id_survey_id_date_a92331d0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_user_id_survey_id_date_a92331d0_uniq UNIQUE (user_id, survey_id, date);


--
-- Name: users_profile users_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: gallery_galleryday_user_id_6c0e1533; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_galleryday_user_id_6c0e1533 ON public.gallery_galleryday USING btree (user_id);


--
-- Name: gallery_photogallery_gallery_day_id_7651b352; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_photogallery_gallery_day_id_7651b352 ON public.gallery_photogallery USING btree (gallery_day_id);


--
-- Name: gallery_videogallery_gallery_day_id_a0bb34a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gallery_videogallery_gallery_day_id_a0bb34a2 ON public.gallery_videogallery USING btree (gallery_day_id);


--
-- Name: mainapp_answers_survey_id_7710a3df; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_answers_survey_id_7710a3df ON public.mainapp_answers USING btree (survey_id);


--
-- Name: mainapp_category_slug_27883014_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_category_slug_27883014_like ON public.mainapp_category USING btree (slug varchar_pattern_ops);


--
-- Name: mainapp_libtext_to_category_id_839e8ee3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_libtext_to_category_id_839e8ee3 ON public.mainapp_libtext USING btree (to_category_id);


--
-- Name: mainapp_personalpost_user_id_dfbde4a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_personalpost_user_id_dfbde4a3 ON public.mainapp_personalpost USING btree (user_id);


--
-- Name: mainapp_post_category_id_1581664c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_post_category_id_1581664c ON public.mainapp_post USING btree (category_id);


--
-- Name: mainapp_post_user_id_5cd7dbd4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_post_user_id_5cd7dbd4 ON public.mainapp_post USING btree (user_id);


--
-- Name: mainapp_useranswer_answer_choice_id_170ad836; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_answer_choice_id_170ad836 ON public.mainapp_useranswer USING btree (answer_choice_id);


--
-- Name: mainapp_useranswer_survey_id_511eb38b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_survey_id_511eb38b ON public.mainapp_useranswer USING btree (survey_id);


--
-- Name: mainapp_useranswer_user_id_f5fa355a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mainapp_useranswer_user_id_f5fa355a ON public.mainapp_useranswer USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_galleryday gallery_galleryday_user_id_6c0e1533_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_galleryday
    ADD CONSTRAINT gallery_galleryday_user_id_6c0e1533_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_photogallery gallery_photogallery_gallery_day_id_7651b352_fk_gallery_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_photogallery
    ADD CONSTRAINT gallery_photogallery_gallery_day_id_7651b352_fk_gallery_g FOREIGN KEY (gallery_day_id) REFERENCES public.gallery_galleryday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_videogallery gallery_videogallery_gallery_day_id_a0bb34a2_fk_gallery_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_videogallery
    ADD CONSTRAINT gallery_videogallery_gallery_day_id_a0bb34a2_fk_gallery_g FOREIGN KEY (gallery_day_id) REFERENCES public.gallery_galleryday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_answers mainapp_answers_survey_id_7710a3df_fk_mainapp_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_answers
    ADD CONSTRAINT mainapp_answers_survey_id_7710a3df_fk_mainapp_survey_id FOREIGN KEY (survey_id) REFERENCES public.mainapp_survey(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_libtext mainapp_libtext_to_category_id_839e8ee3_fk_mainapp_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_libtext
    ADD CONSTRAINT mainapp_libtext_to_category_id_839e8ee3_fk_mainapp_category_id FOREIGN KEY (to_category_id) REFERENCES public.mainapp_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_personalpost mainapp_personalpost_user_id_dfbde4a3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_personalpost
    ADD CONSTRAINT mainapp_personalpost_user_id_dfbde4a3_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_post mainapp_post_category_id_1581664c_fk_mainapp_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_category_id_1581664c_fk_mainapp_category_id FOREIGN KEY (category_id) REFERENCES public.mainapp_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_post mainapp_post_user_id_5cd7dbd4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_post
    ADD CONSTRAINT mainapp_post_user_id_5cd7dbd4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_answer_choice_id_170ad836_fk_mainapp_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_answer_choice_id_170ad836_fk_mainapp_a FOREIGN KEY (answer_choice_id) REFERENCES public.mainapp_answers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_survey_id_511eb38b_fk_mainapp_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_survey_id_511eb38b_fk_mainapp_survey_id FOREIGN KEY (survey_id) REFERENCES public.mainapp_survey(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_useranswer mainapp_useranswer_user_id_f5fa355a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mainapp_useranswer
    ADD CONSTRAINT mainapp_useranswer_user_id_f5fa355a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_profile users_profile_user_id_2112e78d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_2112e78d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

