version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             uvicorn websiteProject.asgi:application --host 0.0.0.0 --port 8000 --reload --log-level debug"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: