# Generated by Django 5.2.3 on 2025-06-17 14:21

import gallery.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[gallery.forms.validate_video_size, gallery.forms.validate_video_duration]),
        ),
    ]
