# Generated by Django 5.2.4 on 2025-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_videogallery_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photogallery",
            name="image",
            field=models.ImageField(upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
