# Generated by Django 5.1.7 on 2025-04-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.CreateModel(
            name='LibText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок мого поля з текстом')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Мій текст належить до Категорії')),
            ],
            options={
                'verbose_name': 'пост адміна для Бібліотеки',
                'verbose_name_plural': 'постИ адміна для бібліотеки',
            },
        ),
        migrations.CreateModel(
            name='LibUserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок посту')),
                ('content', models.TextField(verbose_name='Опис посту')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час посту')),
                ('date', models.DateField()),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Мій текст належить до Категорії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'постЮзерВБібліотеку',
                'verbose_name_plural': 'постиЮзерВБібліотеку Пости',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.survey')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок посту')),
                ('content', models.TextField(verbose_name='Опис посту')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час посту')),
                ('poster', models.ImageField(upload_to='uploads', verbose_name='ПостерДоПерсональногоПосту')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ОсобистийПост',
                'verbose_name_plural': 'Особисті Пости',
                'unique_together': {('user', 'poster', 'date', 'content')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('answer_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.answers')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'survey', 'date')},
            },
        ),
    ]
