# Generated by Django 5.1.7 on 2025-03-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='CheckForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата опитування')),
                ('answer1', models.BooleanField(default=False, verbose_name='мені сумно')),
                ('answer2', models.BooleanField(default=False, verbose_name='мені весело')),
                ('answer3', models.BooleanField(default=False, verbose_name='мені норм')),
            ],
            options={
                'verbose_name': 'Опитуваннячко',
                'verbose_name_plural': 'Опитування',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'УсіЗображення',
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ДумкаФорма',
                'verbose_name_plural': 'ДумкиФорма',
            },
        ),
        migrations.CreateModel(
            name='LibText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок мого поля з текстом')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Мій текст належить до Категорії')),
            ],
            options={
                'verbose_name': 'Мій постик',
                'verbose_name_plural': 'Мої постики',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Дата та час посту')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок посту')),
                ('content', models.TextField(verbose_name='Опис посту')),
                ('poster', models.URLField(default='https://images.pexels.com/photos/147465/pexels-photo-147465.jpeg?auto=compress&cs=tinysrgb&w=600', verbose_name='Постер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('teg', models.ManyToManyField(blank=True, related_name='posts', to='mainapp.teg', verbose_name='Хештеги')),
            ],
            options={
                'verbose_name': 'ПостБложний',
                'verbose_name_plural': 'ПостиБложні',
            },
        ),
    ]
