# Generated by Django 5.2.1 on 2025-05-15 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalpost',
            unique_together={('user', 'date', 'content')},
        ),
        migrations.RemoveField(
            model_name='personalpost',
            name='poster',
        ),
    ]
