# Generated by Django 5.1.7 on 2025-04-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuserpost',
            name='to_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.category', verbose_name='Мій текст належить до Категорії'),
        ),
    ]
