# Generated by Django 5.1.7 on 2025-04-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_libuserpost_to_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Дата та час посту')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок посту')),
                ('content', models.TextField(verbose_name='Опис посту')),
                ('poster', models.ImageField(upload_to='uploads')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.category', verbose_name='Категорія')),
                ('teg', models.ManyToManyField(blank=True, related_name='posts', to='mainapp.teg', verbose_name='Хештеги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ПостБложний',
                'verbose_name_plural': 'ПостиБложні',
            },
        ),
        migrations.DeleteModel(
            name='LibUserPost',
        ),
    ]
