# Generated by Django 5.2.1 on 2025-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_personalpost_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="poster",
        ),
    ]
