# Generated by Django 5.1.7 on 2025-04-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_post_delete_libuserpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libtext',
            options={'verbose_name': 'пост зАдмінки для Бібліотеки', 'verbose_name_plural': 'постИ з адмінки для бібліотеки'},
        ),
    ]
