# Generated by Django 5.1.7 on 2025-04-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_libtext_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'запис юзера в бібл', 'verbose_name_plural': 'записи юзера в бібл'},
        ),
    ]
