# Generated by Django 5.1.7 on 2025-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='marker',
            field=models.CharField(choices=[('good', 'Добре'), ('neutral', 'Середнє'), ('bad', 'Погано')], default='neutral', max_length=10),
            preserve_default=False,
        ),
    ]
