# Generated by Django 5.2.3 on 2025-06-17 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_libtext_to_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="libtext",
            name="title",
            field=models.CharField(max_length=30, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="libtext",
            name="title_en_gb",
            field=models.CharField(max_length=30, null=True, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="libtext",
            name="title_uk",
            field=models.CharField(max_length=30, null=True, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="libtext",
            name="to_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libtexts",
                to="mainapp.category",
                verbose_name="категорія",
            ),
        ),
        migrations.AlterField(
            model_name="personalpost",
            name="content",
            field=models.TextField(verbose_name="опис"),
        ),
        migrations.AlterField(
            model_name="personalpost",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата та час"),
        ),
        migrations.AlterField(
            model_name="personalpost",
            name="title",
            field=models.CharField(max_length=30, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="personalpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="mainapp.category",
                verbose_name="категорія",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="опис"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_created=True, verbose_name="дата та час"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30, verbose_name="заголовок"),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
    ]
