# Generated by Django 5.2.4 on 2025-07-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_libtext_title_alter_libtext_title_en_gb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="teg",
        ),
        migrations.DeleteModel(
            name="Teg",
        ),
    ]
