# Generated by Django 5.2.5 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_post_teg_delete_teg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='choice_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answers',
            name='choice_text_en_gb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='choice_text_uk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_en_gb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_uk',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
