# Generated by Django 5.1.7 on 2025-04-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_useranswer_date_alter_useranswer_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Дата та час посту')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок посту')),
                ('content', models.TextField(verbose_name='Опис посту')),
                ('poster', models.URLField(default='https://images.pexels.com/photos/147465/pexels-photo-147465.jpeg?auto=compress&cs=tinysrgb&w=600', verbose_name='Постер')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ОсобистийПост',
                'verbose_name_plural': 'Особисті Пости',
                'unique_together': {('user', 'poster', 'date', 'content')},
            },
        ),
    ]
