# Generated by Django 5.1.7 on 2025-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_personalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата та час посту'),
        ),
    ]
